services:
  nginx:
    image: 'nginx:1.23.3'
    volumes:
      - 'uploads:/etc/file-server/uploads'
      - './passwords:/etc/file-server/passwords:ro'
      - './upload.html:/etc/file-server/www/upload.html:ro'
      - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8000:80'
    depends_on: ['mover']

  mover:
    build:
      context: ./mover
      dockerfile: ./Dockerfile
    volumes:
      - 'uploads:/etc/file-server/uploads'

volumes:
  uploads:
